### ISSUE TITLE
Delete haplotype frequencies for a failed HF set as part of import clean up

### ISSUE THREAD

**Issue by zabeen** [Anthony-Nolan/Atlas#1015]
## Problem

Currently if something goes wrong when new rows are being written to `MatchPrediction.HaplotypeFrequencies`, the HF set that the frequencies belong to are not activated (as that is the last step of import), and the rows remain in the table ([see importer service](https://github.com/Anthony-Nolan/Atlas/blob/master/Atlas.MatchPrediction/Services/HaplotypeFrequencies/Import/FrequencySetImporter.cs#L107)). With message replays this leads to a lot of junk data in the shared db.

## Solutions

1) Wrap the [bulk insert of haplotype frequencies](https://github.com/Anthony-Nolan/Atlas/blob/master/Atlas.MatchPrediction.Data/Repositories/HaplotypeFrequenciesRepository.cs#L28) in a transaction ([see this article](https://learn.microsoft.com/en-us/dotnet/framework/data/adonet/sql/transaction-and-bulk-copy-operations))
  - Note: if this is a viable option, refactor `HaplotypeFrequenciesRepository` to use [common `BulkInsert` code](https://github.com/Anthony-Nolan/Atlas/tree/master/Atlas.Common/Sql/BulkInsert) as part of this ticket.

or 

2) Catch any Sql exceptions that take place during the [frequency storage step](https://github.com/Anthony-Nolan/Atlas/blob/master/Atlas.MatchPrediction/Services/HaplotypeFrequencies/Import/FrequencySetImporter.cs#L175), and call a new method to delete all rows in `MatchPrediction.HaplotypeFrequencies` with the failed set id.

**Comment by zabeen** [comment]
After going through the errors on last import with @IgorKupreychik it seems that the "junk" rows are actually being caused by HF sets failing to activate, due to an active set with same metadata already existing on the HF set table.

Therefore both solutions listed above would be valid. 

The first solution would delete any rows where an exception occured during frequency upload, e.g., duplicate HF rows.
The second solution should be applied during set activation step, where if a set [fails to activate](https://github.com/Anthony-Nolan/Atlas/tree/master/Atlas.MatchPrediction/Services/HaplotypeFrequencies/Import/FrequencySetImporter.cs#L110), then all its rows should be deleted.

**Comment by IgorKupreychik** [comment]
@zabeen, some notes regarding the solutions 1:
- it doesn't make sense to add SqlBulkCopyOptions.UseInternalTransaction option since it's a single insert. Yes, with multiple rows, but still it just inserts those rows in to one table, in this case execution context is already transactional, so it's not necessary to specify additional flags
- Regarding using of common BulkInsert. Since the type of the 'Id' property in IBulkInsertModel is int, but the type of the Id of HaplotypeFrequency is long, this task doesn't seem to be a very simple. We probably need to make the type of IBulkInsertModel.Id generic, but it will cause a lot of other changes in BulkInsertRepository and other existing classes that implement IBulkInsertModel. So, if we really need this, I'd propose to create a separate ticket for this refactoring, since it's not really related to the current one.

**Comment by zabeen** [comment]
@IgorKupreychik please add integration tests for the deletion logic ([existing tests here](https://github.com/Anthony-Nolan/Atlas/blob/master/Atlas.MatchPrediction.Test.Integration/IntegrationTests/Import/ImportTests.cs)).

**Comment by zabeen** [comment]
### Testing

- feature cannot be tested manually, but we have automated unit and integration tests covering it.
- 
- regression test: import a HF set file and ensure it imports successfully.

**Comment by zabeen** [comment]
@IgorKupreychik please update the product changelog, thanks.

**Comment by DmitriyShcherbina** [comment]
@zabeen Regression testing status: Ok


![Image](https://github.com/Anthony-Nolan/Atlas/assets/107943429/9e8986c0-7311-42a1-8147-ac0c4239e8c8)
