### ISSUE TITLE
Missing Match Prediction Logs

### ISSUE THREAD

**Issue by zabeen** [Anthony-Nolan/Atlas#1032]
**Describe the bug**
When I run the AI query that looks for traces and events by atlas search request ID, I do not see these expected log entries:
"MatchPrediction: Expand patient phenotype"
"MatchPrediction: Expand donor genotype"
"MatchPrediction: Calculate likelihoods for genotypes"

**To Reproduce**
1. Run any search with match prediction enabled, and wait until it has completed with success.
2. Open Application Insights in Azure and run the following query:
```
traces  
|union customEvents
|union exceptions
| where customDimensions["SearchRequestId"]=="paste-atlas-search-request-id-here"
| project timestamp, itemType, operation_Name, message = case(itemType == "customEvent", name, itemType == "exception", strcat(outerMessage," - ",innermostMessage), message), customDimensions, invocationId = tostring(customDimensions["InvocationId"])
| order by timestamp desc
| where message startswith "MatchPrediction"
```
You will not see any messages returned.

**Comment by IgorKupreychik** [comment]
@zabeen you don't see those messages since for all messages with prefix "MatchPrediction: " log level is set to 'Verbose', but the log level for functions is set to 'Info'. We can either change the functions log level to 'Verbose' or update those several messages with the prefix "MatchPrediction: " and set log level for them to 'Info'. Please let me know what option you would like to implement.

**Comment by zabeen** [comment]
@IgorKupreychik ah, ok! That's fine then, I thought something had gone wrong during all the refactoring that has been done to match prediction. Leave everything as is then, will close this ticket.
