### ISSUE TITLE
Dead-lettered searchable donor updates on LIVE-WMDA-ATLAS

### ISSUE THREAD

**Issue by zabeen** [Anthony-Nolan/Atlas#1053]
There are over 500 DL updates on `matching-transient-a` sub that mostly date from 16th August 2023.

1) why did they dead-letter?
2) how do we ensure that these donors are in correct state within the active matching algorithm? The large number precludes a manual sql query.
3) how do we force updates of the affected donors so the final state is in line with the donor store?

**Comment by zabeen** [comment]
### HLD

- Write two DLQ reader functions on donor import functions app - one for each `transient` sub on the `updated-searchable-donors` topic
 - Each function should batch read the DLQ ([existing example](https://github.com/Anthony-Nolan/Atlas/blob/a3a993d83cd68d064b1ffe78d02adf9dc64ae38a/Atlas.MatchPrediction.Functions/Functions/MatchPredictionFunctions.cs#L76C61-L76C61)) and extract the donor Ids
 - Ids are then passed to a service that will check against the Atlas donor store and [save updates for each ID](https://github.com/Anthony-Nolan/Atlas/blob/master/Atlas.DonorImport/Services/DonorUpdates/DonorUpdatesSaver.cs):
   - if ID exists, save a `IsAvailableForSearch: true` update 
   - if ID not found, save a `IsAvailableForSearch: false` update

**Comment by zabeen** [comment]
@IgorKupreychik re: point 1 on the card, I doubt AI will have any info after so many months, so you can just focus on the dev work :)

**Comment by zabeen** [comment]
### Testing Notes

1. Force `updated-searchable-donors` messages to dead-letter, by breaking the db connection string on the [donor management functions app](https://portal.azure.com/#@ukmarrow.org/resource/subscriptions/6114522f-eea5-44ab-94ab-af37ffffc4d3/resourceGroups/DEV-ATLAS-RESOURCE-GROUP/providers/Microsoft.Web/sites/DEV-ATLAS-MATCHING-DONOR-MANAGEMENT-FUNCTION/appServices).
2. Upload a donor import file with new donor and delete donor updates.
3. Once the update messages from the file import have dead-lettered, you should see the messages disappear off the DLQ and be republished to the same topic after a couple of minutes. The re-published messages should have the correct contents.
4. Fix the connection string on the functions app and check the update messages are consumed and applied to the matching database using the [donor debug endpoint on the matching algorithm functions app](https://portal.azure.com/#view/WebsitesExtension/FunctionMenuBlade/~/functionOverview/resourceId/%2Fsubscriptions%2F6114522f-eea5-44ab-94ab-af37ffffc4d3%2FresourceGroups%2FDEV-ATLAS-RESOURCE-GROUP%2Fproviders%2FMicrosoft.Web%2Fsites%2FDEV-ATLAS-MATCHING-ALGORITHM-FUNCTIONS%2Ffunctions%2FGetDonorsFromActiveDb).

**Comment by daria-sorokina-da** [comment]
### Testing Results

1. Broke the SQL connection strings in [DEV-ATLAS-MATCHING-DONOR-MANAGEMENT-FUNCTION](https://portal.azure.com/#@ukmarrow.org/resource/subscriptions/6114522f-eea5-44ab-94ab-af37ffffc4d3/resourceGroups/DEV-ATLAS-RESOURCE-GROUP/providers/Microsoft.Web/sites/DEV-ATLAS-MATCHING-DONOR-MANAGEMENT-FUNCTION/configuration) - changed the dev-atlas-sql-server.database.windows.net to dev-atlas-sql-server**r**.database.windows.net
2. Sent a message in dev-atlas service bus > updated-searchable-donors
3. The message got "stuck" in matching-transient-a and matching-transient-b subscriptions, I couldn't see the moment when it was dead-lettered as it returned to the main queue right away
4. I could see in the log that the move of the message happened (i.e. log "_Message processing has been stopped or cancelled (namespace='dev-atlas.servicebus.windows.net', enityPath='updated-searchable-donors/Subscriptions/matching-transient-a/$DeadLetterQueue/Subscriptions/matching-transient-a', singleDispatch='False', isSessionsEnabled='False', functionId='Atlas.MatchingAlgorithm.Functions.DonorManagement.Functions.DonorManagementFunctions.ProcessDifferentialDonorUpdatesForMatchingDbADeadLetterQueueListener')_"
5. I fixed the connection string
6. The message got processed

The mechanism worked as expected - the deadlettered message was returned to the topic.

**But there's a downside:**
I noticed that the CPU grew during the processing of the message back and forth - I saw messages in the logs Host CPU threshold exceeded (87 >= 80), Host CPU threshold exceeded (85 >= 80).
So looks like the operation of moving message back and forth was quite expensive CPU-wise, and in case the message deadletters fo a reason, it will stay in the queue forever, draining the CPU.
Do we want to introduce a mechanism to only retry the message some fixed number of times, for a fixed period of time, so that the messages do not get stuck?
@zabeen

**Comment by zabeen** [comment]
> But there's a downside:
I noticed that the CPU grew during the processing of the message back and forth - I saw messages in the logs Host CPU threshold exceeded (87 >= 80), Host CPU threshold exceeded (85 >= 80).
So looks like the operation of moving message back and forth was quite expensive CPU-wise, and in case the message deadletters fo a reason, it will stay in the queue forever, draining the CPU.
Do we want to introduce a mechanism to only retry the message some fixed number of times, for a fixed period of time, so that the messages do not get stuck?

@daria-sorokina-da The CPU spike is surprising! As the DL message is just being read and a new message being queued for publishing. Updates are being published and read off the main queue in batches via cron functions (they are not sb-triggered functions), so I am not sure why this would cause a CPU spike, even if it was happening in an indefinite loop. Especially if it's only one or two messages!

It's hard to say without more investigation, but perhaps the broken db connection is causing the spike, rather than the replaying of messages? One way to verify this would be to cause the messages to dead-letter via another mechanism, but I can't think of an easy way to do that! Can you? 🤔

**Comment by zabeen** [comment]
General update, on 15th October another 7K update messages dead-lettered on live-wmda-atlas update queue due to the following exception: "Exception while executing function: ProcessDifferentialDonorUpdatesForMatchingDbA - Cannot renew locks on a message batch with a lock expiry in the past." [link to example in AI](https://portal.azure.com/#blade/AppInsightsExtension/DetailsV2Blade/DataModel/%7B%22eventId%22:%221116a578-6b95-11ee-b0b0-3b40075ee323%22,%22timestamp%22:%222023-10-15T19:57:01.7601886Z%22%7D/ComponentId/%7B%22Name%22:%22LIVE-WMDA-ATLAS%22,%22ResourceGroup%22:%22LIVE-WMDA-ATLAS-RESOURCE-GROUP%22,%22SubscriptionId%22:%229653b669-14c1-4b9b-8c23-b9597256840c%22%7D)

**Comment by zabeen** [comment]
Update: on release of new DLQ listener functions to live-wmda, all 7K+ dead-lettered donor updates were re-published and processed successfully.
