### ISSUE TITLE
Cache Feature Flag values

### ISSUE THREAD

**Issue by zabeen** [Anthony-Nolan/Atlas#1080]
FF added as part of #1066 will be checked once every search, which could mean checking its value stored in remote azure config 100s of times a day when run on WMDA live.

Caching would minimise the number of http calls.

But if we want to enable a feature without release or restart, how long should the cache expiry period be?

Alternatively, cache could have a long expiry, and instead add a new function that forces the refresh of Atlas feature flag cache?

**Comment by zabeen** [comment]
@IgorKupreychik Now that feature flag management is live, could you please investigate what we would need to do for this ticket? We may not do the work now, if #1067 is done first, but would be good to know for future.

**Comment by IgorKupreychik** [comment]
@zabeen, there is not much options for caching here. We can use in-memory cache, but, since it's Azure function, after 5 minutes of idle time, this cache will be reset. We can use a distributed Redis cache, but in this case we will still have to make an additional call (not to Azure Configuration, but to Redis).
From the other side, Azure Configuration has a built-in caching mechanism where the flag value is cached on the Azure side with a default TTL = 30sec. This time can be simply configured if needed (https://learn.microsoft.com/en-us/azure/azure-app-configuration/use-feature-flags-dotnet-core?tabs=core6x).
