### ISSUE TITLE
Repeat search failing at matching algorithm 

### ISSUE THREAD

**Issue by zabeen** [Anthony-Nolan/Atlas#1100]
```
Inner exception System.Collections.Generic.KeyNotFoundException handled at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw
System.ThrowHelper.ThrowKeyNotFoundException |   |  
Atlas.RepeatSearch.Services.Search.RepeatSearchDifferentialCalculator.LookupDonorIdFromCode | RepeatSearchDifferentialCalculator.cs | 81

```

[Example from AI](https://portal.azure.com/#view/AppInsightsExtension/DetailsV2Blade/ComponentId~/%7B%22SubscriptionId%22%3A%229653b669-14c1-4b9b-8c23-b9597256840c%22%2C%22ResourceGroup%22%3A%22LIVE-WMDA-ATLAS-RESOURCE-GROUP%22%2C%22Name%22%3A%22LIVE-WMDA-ATLAS%22%2C%22LinkedApplicationType%22%3A0%2C%22ResourceId%22%3A%22%252Fsubscriptions%252F9653b669-14c1-4b9b-8c23-b9597256840c%252FresourceGroups%252FLIVE-WMDA-ATLAS-RESOURCE-GROUP%252Fproviders%252FMicrosoft.Insights%252Fcomponents%252FLIVE-WMDA-ATLAS%22%2C%22ResourceType%22%3A%22microsoft.insights%252Fcomponents%22%2C%22IsAzureFirst%22%3Afalse%7D/DataModel~/%7B%22eventId%22%3A%22cc86cd5c-6d7d-11ee-9496-43f2be1459c7%22%2C%22timestamp%22%3A%222023-10-18T06%3A15%3A55.116Z%22%2C%22cacheId%22%3A%22cefe2841-a008-45ac-ab87-c9ef779ab8c3%22%2C%22eventTable%22%3A%22exceptions%22%7D)

Example failed repeat search request from `UAT-WMDA-ATLAS` on 18th Oct 2023:
```
  "SearchRequestId": "349ce783-cfaa-4b00-88d0-c3728e6f64fc",
  "RepeatSearchRequestId": "a14375d6-f5e2-4770-aa85-7f3ec3725c5d"
```

**Comment by zabeen** [comment]
### Testing Notes

- Run repeat search E2E test covering new match

**Comment by daria-sorokina-da** [comment]
**Scenarios**

1) Some of the donors in the search are the same as they were (not updated since cut-off date)

First search (Canonical) returns donors [1, 2]
Repeat search returns donors [2, 3]
Updated donors since cut-off date returns [1,3,5,6] - needed only to figure out which donors were updated

**New**: [3] -> **[{3, <atlas id of donor 3}>}]**
**Updated**: [2] -> filter out only the ones that were updated since cut-off date -> **[]**
**Delete**: [1] -> **[{1,<atlas id of donor 1}>}]**

2) Some of the donors in the search have been updated

First search (Canonical) [1,2]
Repeat [2,3]
Updated since cut-off date returns [1,2,5,6] - needed only to figure out which donors were updated

**New**: [3] -> **[{3, <atlas id of donor 3}>}]**
**Updated**: [2] -> filter out only the ones that were updated since cut-off date -> **[2,<atlas id of donor 2}>}]**
**Delete**: [1] -> **[{1,<atlas id of donor 1}>}]**

==============================================================

**Test scenarios:**
1) Donor gets deleted
First search: [1,2]
Delete donor 2 (via donor update file)
Repeat searct => {new: [], updated: [], deleted: [2]}
2) Donor gets added
First search: [1,2]
Add donor 3 that matches the search (via donor update file)
Repeat search => {new: [3], updated: [], deleted: []}
3) Donor gets updated but still a match
First search: [1,2]
Update donor 2 with update file, but make sure that the donor is still a match
Repeat search => {new: [], updated: [2], deleted: []}
4) Donor gets updated and not a match anymore
First search: [1,2]
Update donor 2 with update file, and change its HLA so that it's not a match anymore
Repeat search => {new: [], updated: [], deleted: [2]}

**Comment by DmitriyShcherbina** [comment]
@zabeen @daria-sorokina-da @IgorKupreychik Testing status: Ok
But during testing process I faced with strange behaviour, so I created this ticket https://github.com/Anthony-Nolan/Atlas/issues/1108

**Comment by RimkePostel** [comment]
Testing in SBX approved
