### ISSUE TITLE
Failed Searchable Donor Update not applied upon replay

### ISSUE THREAD

**Issue by zabeen** [Anthony-Nolan/Atlas#1140]
- update that failed HLA validation due to "MAC not found error" (see #1137) was still recorded in matching algorithm db `DonorManagementLogs` table, even though the HLA was not actually updated
  -  I could tell this from the `SequenceNumberOfLastUpdate` which belonged to the update message that failed validation.
- after resolving #1137, the replayed update now passed HLA validation, but the new HLA info was not applied to the donors table. This is because its published date was not newer than that logged in the `DonorManagementLogs` table.
- I manually re-sent the message with same contents but a newer published datetime. Only then was the update applied to both the `Donors` and `DonorManagementLogs` tables

I had a quick look at the code and couldn't immediately see why the failed update was being logged to `DonorManagementLogs` table, so it needs more time spent on investigation.

---
Although this is a live bug, it is not critical as there is a manual workaround, and #1139 will circumvent this bug once it is deployed.

**Comment by zabeen** [comment]
@SergeyEzh this is not a critical bug to fix, but I am wondering why a failed update is being logged to the donor management log table - it should not get that far. I am hoping this is not indicative of a larger problem! So would appreciate you stepping through the code to determine the exact cause.

I can walk through the donor update workflow with you tomorrow at our meeting.

**Comment by SergeyEzh** [comment]
@zabeen, It happens because hla metadata lookup happens much later and separately from other validation:
First part of validation happens  in `Atlas.MatchingAlgorithm.Services.DonorManagement.DonorUpdateProcessor`
![Image](https://github.com/Anthony-Nolan/Atlas/assets/151528303/ad937f0a-fc7c-4272-8bb9-7dcdefd83b11)
On the line 236, `ConvertSearchableDonorUpdatesAsync` is called and subsequently calls `Atlas.MatchingAlgorithm.Validators.DonorInfo.DonorUpdateMessageValidator` which validates objects against simple rules (e.g. properties are not null, and so on). At this stage records which didn't pass this simple validation is filtered out and call on line 243 get only valid records.

Then eventually execution flow comes to `Atlas.MatchingAlgorithm.Services.DonorManagement.ApplyDonorUpdates`:


![Image](https://github.com/Anthony-Nolan/Atlas/assets/151528303/1bdfc561-24be-4256-b800-a7ddafa6a34b)

Line 181 has a call to `AddOrUpdateDonors` which calls `Atlas.MatchingAlgorithm.Services.Donors.DonorService.CreateOrUpdateDonorBatch`. This methods performs hla metadata lookup and filters out records for which it didn't find metadata for hla. Then it updates Donors table.

As you can see on the screenshot it doesn't returns information which Donors was updated. And `CreateOrUpdateManagementLogBatch` on line 183 updates log table regardless whether donor was saved or not.

PS. I'm not sure that I use correct terminology about that hla stuff, I can show you details on tomorrow's meeting if it is needed.

**Comment by zabeen** [comment]
Great work @SergeyEzh , I understood your comment just fine. :)

**Comment by SergeyEzh** [comment]
As one of possible solution I propose just to return list of actually updated records from `AddOrUpdateDonors` and use that list in `CreateOrUpdateManagementLogBatch`

**Comment by zabeen** [comment]
As discussed with @SergeyEzh , regression test to be added to cover edge case

**Comment by SergeyEzh** [comment]
> As discussed with @SergeyEzh , regression test to be added to cover edge case

Added to PR. I haven't found suitable test fixture so created a new one. Please review.

**Comment by zabeen** [comment]
### Testing

- Regression: All Atlas E2E tests (including donor update) passing on DEV
- Fix: TBC
