### ISSUE TITLE
Profile Atlas in Azure

### ISSUE THREAD

**Issue by zabeen** [Anthony-Nolan/Atlas#1208]
https://learn.microsoft.com/en-us/azure/azure-monitor/profiler/profiler-overview

See notes from previous attempt: https://github.com/Anthony-Nolan/Atlas/issues/1119

Previous attempt to profile atlas failed because A.I. profiler can only run on app service plan - not any functions plans.

1) Create a new spike branch from git tag `stable/1.6.1` which is current stable Atlas version.
2) On spike branch, make necessary terraform script changes to convert elastic plans to app service plans.
3) Enable profiler on both `matching` and `<env>-atlas-functions` apps, as described in #1119.
4) Deploy spike branch to dev-atlas and check the plans have updated as required.
5) Run test searches with match prediction ON, and see if profiler captures data.

If test successful, then we can discuss with wmda about deploying the spike to UAT-WMDA-ATLAS, and running performance tests there, as the data there is similar to live-atlas-wmda.

**Comment by SergeyEzh** [comment]
@zabeen, I was able to successfully apply terraform configuration for profiling. New functions were deployed on app service plan and regular ones were disabled. I manually stated profiling session and got some results:

![Image](https://github.com/Anthony-Nolan/Atlas/assets/151528303/4fafc23f-4b9e-47f4-af83-5b9d04fa4e21)

Also it has showed some recommendations:

![Image](https://github.com/Anthony-Nolan/Atlas/assets/151528303/7c971f3f-3314-49c1-a826-9df9015e1a5d)
Don't be confused: 'dev-atlas-matching-algorithm-functio...' it's 'dev-atlas-matching-algorithm-functions-temp'. It isn't recommendations from 'before profiling' time. In the first deployment, profiled functions had 'temp' in the end of their names. But they had some ID conflict because it was generated by truncation of their names and with 'temp' at the end they were the same.

However, it couple things confuse me:

- Azure only let's to start profiler session, there's no possibility to stop it. Azure decides how long in should be. I tried several times and it always were different durations of sessions.
- For some reason there was only results for one of profiled functions. Initially I thought that I enabled profiling only for one of them, but then I noticed that I've got recommendations for both functions. So don't know what to think :)
- The results were like on that screenshot:


![Image](https://github.com/Anthony-Nolan/Atlas/assets/151528303/93954dd3-080f-469e-aaf4-30eb92568edd)

Code were working most of the time is system's or azure's code. I suppose this is because profiler session relative long (7-20 mins) and I was sending search requests manually from time to time and profiler doesn't exclude all service code from profiling. I think it supposed to run profiler sessions on some load to get adequate results.

- Also, it can't really profile memory like I would expect from profiler tools I used before. It can't show how much memory used and which objects use this memory. As I understood from documentation, I shows only memory allocation operations and one can examine amount of allocations and decide if there's too much of them.
 

Results are still there in azure, you can look at [them](https://portal.azure.com/#view/AppInsightsExtension/ServiceProfilerTriggerConfigurationV2/ComponentId~/%7B%22SubscriptionId%22%3A%226114522f-eea5-44ab-94ab-af37ffffc4d3%22%2C%22ResourceGroup%22%3A%22DEV-ATLAS-RESOURCE-GROUP%22%2C%22Name%22%3A%22DEV-ATLAS%22%2C%22LinkedApplicationType%22%3A0%2C%22ResourceId%22%3A%22%2Fsubscriptions%2F6114522f-eea5-44ab-94ab-af37ffffc4d3%2FresourceGroups%2FDEV-ATLAS-RESOURCE-GROUP%2Fproviders%2FMicrosoft.Insights%2Fcomponents%2FDEV-ATLAS%22%2C%22ResourceType%22%3A%22microsoft.insights%2Fcomponents%22%2C%22IsAzureFirst%22%3Afalse%7D/TimeContext~/%7B%22durationMs%22%3A86400000%2C%22createdTime%22%3A%222024-02-19T12%3A34%3A47.473Z%22%2C%22isInitialTime%22%3Afalse%2C%22grain%22%3A1%2C%22useDashboardTimeRange%22%3Afalse%7D/EnablingTrigger/curated)
