### ISSUE TITLE
Add debug endpoint to query application insights for HLA expansion failure

### ISSUE THREAD

**Issue by zabeen** [Anthony-Nolan/Atlas#1231]
https://learn.microsoft.com/en-us/azure/azure-monitor/logs/api/overview

- set up authentication
- formulate request with query
- parse results

### HLD
- add GET endpoint to MatchingAlgorithm.Functions app
- query:
```
AppEvents
| where Name startswith "HLA Expansion"
| extend
    DonorInfo = parse_json(tostring(Properties["DonorInfo"])),
    Locus = tostring(Properties["Locus"]),
    HlaName = tostring(Properties["HlaName"])
| distinct
    InvalidHLA = strcat(Locus, HlaName),
    ExternalDonorCode = tostring(DonorInfo["ExternalDonorCode"]),
    ExceptionType = tostring(Properties["InnerExceptionType"])
| summarize
    ExceptionType = make_list(ExceptionType, 10)[0],
    ExternalDonorCodes = make_list(ExternalDonorCode, 1000),
    DonorCount = count() by InvalidHLA
| order by DonorCount desc
```

**Comment by SergeyEzh** [comment]
@zabeen, PR is created for this item (https://github.com/Anthony-Nolan/Atlas/pull/1248). Here is just couple notes:

I have added new release variable `AZURE_TENANT_ID`. Therefore, it should be set in release pipelines on both AN and WMDA  instances of  Azure Devops. However, I noticed that existing release variable (`DATABASE_SERVER_AZUREAD_ADMINISTRATOR_TENANTID`) has the same value as currently we need. So we can avoid updating azure devops by reusing this variable. But I'm not sure if it always be the same.

Also, do I need add this new release variable to README_Configuration.md? 

Currently, result looks like that:

![Image](https://github.com/Anthony-Nolan/Atlas/assets/151528303/49a0784b-0f49-43d1-92db-6b51c8a87d2b)

Do I need unwrap `ExternalDonorCodes`? I didn't do it initially, because `ExceptionType` and `ExternalDonorCodes` have the same type in results, so I can't distinguish them without examining property names. But it would reduce flexibility if query will be changed. What is the priority?

**Comment by zabeen** [comment]
> Also, do I need add this new release variable to README_Configuration.md?
yes please

> Do I need unwrap ExternalDonorCodes? I didn't do it initially, because ExceptionType and ExternalDonorCodes have the same type in results, so I can't distinguish them without examining property names. 
Please unwrap, and map to a new model in `Debug.Client.Models` project, this will be the return type in the `Debug.Client` method.

> But it would reduce flexibility if query will be changed. What is the priority?
This query shouldn't change anytime soon. It's been in use for a while and is working well (at least, pre-workspace migration!)
