### ISSUE TITLE
HLA (MAC) Validation

### ISSUE THREAD

**Issue by mmelchers** [Anthony-Nolan/Atlas#628]
We were wondering to what extent ATLAS is able to validate the HLA that is coming in with a search and with the donors. We were able to find some code for generating and updating the storage tables and for importing MAC codes and valid alleles, but we haven't been able to find how you are doing MAC code verification itself. This because a MAC code (just the letters) could exist, but when one of its decoded alleles (so including locus and first field) does not exist, it automatically makes this particular HLA typing invalid. How do you check that? Which part of the ATLAS code base takes care of that?

**Comment by zabeen** [comment]
Existing MACs that expand to an "invalid" list of alleles would be discovered during lookup of the HLA typing within the [HLA metadata dictionary](https://github.com/Anthony-Nolan/Atlas/tree/master/Atlas.HlaMetadataDictionary) component, causing an invalid HLA exception.

This integration test covers the scenario you describe:
https://github.com/Anthony-Nolan/Atlas/blob/761ce4fed5b94917d8b2ef830e8e37d41619cbef/Atlas.HlaMetadataDictionary.Test/IntegrationTests/Tests/SearchRelatedMetadataServiceTests.cs#L59

**Comment by benbelow** [comment]
FWIW I believe this is the relevant ADR for this decision https://github.com/Anthony-Nolan/Atlas/blob/master/ArchitecturalDecisionRecord/Phase1/003-MultipleAlleleCodeLookup_Storage.md

this ADR covers the differences between Atlas and the old Anthony Nolan algorithm more than it makes this specific decision explicit. I think this line `Generic MACs only contain information about the alleles' second fields, and are applicable to any first field. At time of lookup, the given first field will need to be added to all expanded second fields before individual alleles can be processed.` implies what Zabeen said above - although it could be clearer. If I get a free second I can add the implication that `This means that it is possible to expand a MAC to invalid alleles - these will not be validated by the MAC component, but each individually expanded allele should be validated by the appropriate nomenclature HLA Metadata Dictionary`

I wonder if it's also worth emphasizing that this approach allows the MAC lookup component to be nomenclature agnostic - as otherwise the expansion of a single MAC/first field/locus could be valid in one nomenclature version, and not the next
