### ISSUE TITLE
exceptions in application insights log

### ISSUE THREAD

**Issue by mmelchers** [Anthony-Nolan/Atlas#678]
While performing tests on ATLAS I found that the logs were filled with various exceptions. Please investigate why this happens and fix them

**Comment by luken-an** [comment]
@benbelow - test comment

**Comment by luken-an** [comment]
@benbelow test comment 2

**Comment by zabeen** [comment]
@mmelchers I am closing this ticket because it's a year old and has no specific details about what the exceptions were, and the circumstances of them being raised. A new ticket(s) can be raised to report specific exceptions/bugs that we encounter during the 2023 round of system-level integration testing.
