### ISSUE TITLE
Search failed at stage: Matching Algorithm

### ISSUE THREAD

**Issue by mmelchers** [Anthony-Nolan/Atlas#680]
When running standard searches I get several searches that fail to finish. The message on the audit topic of the search-results-ready subscription mentions the following: 

{
  "FailureMessage": "Search failed at stage: Matching Algorithm. See Application Insights for failure details.",
  "MatchingAlgorithmTime": "00:00:00",
  "MatchPredictionTime": "00:00:00",
  "OverallSearchTime": "00:00:00",
  "SearchRequestId": "<OBFUSCATED>",
  "WasSuccessful": false,
  "RepeatSearchRequestId": null,
  "BlobStorageContainerName": null,
  "ResultsFileName": null,
  "NumberOfResults": null,
  "MatchingAlgorithmHlaNomenclatureVersion": null
}

Searching for the indicated searchRequestId in the application insights log leads to the following results: 

Failed to run search with id XXXXX. Exception: Microsoft.Data.SqlClient.SqlException (0x80131904): Database 'testing-atlas-matching-b' on server 'testing-atlas-sql-server.database.windows.net' is not currently available.  Please retry the connection later.  If the problem persists, contact customer support, and provide them the session tracing ID of '{9FD3D9AE-093C-4A9C-8131-1BC895301A8C}'.

After a retry the search seems to finish successfully, but how is our application supposed to know whether the search failed forever or just once and it worked after a retry? The failure message ended up in the "search results ready" topic.

**Comment by benbelow** [comment]
In this specific case, this error message is an expected one, as you're using a database with auto-pause enabled - auto-pause will always cause connections to fail like this when asleep, and such connections will fail for a minute or so when the database wakes up. Database connectivity issues are one of the most likely transient errors, so we should certainly retain our retry logic here. As long as you don't plan to enable auto-pause in live, you shouldn't see this in a production environment. 

> After a retry the search seems to finish successfully, but how is our application supposed to know whether the search failed forever or just once and it worked after a retry? The failure message ended up in the "search results ready" topic.

Ultimately the only way to "know" this is to trust the most recent message from Atlas, and ensure that your consumer maintains ordering. We can't really know the difference between a transient and a persistent error without retrying, so the answer to "how do we know" is - a transient error will be followed by a success message, a persistent one will not be.

___________________________

I do think there's scope to do some work to improve the messaging when the failures are due to input validation failures though - I've noticed a few cases where the input HLA is being rejected, and it seems that the current approach of "Check Application Insights" logs isn't one that will work for you - would you like me to raise a new issue to add a more detailed error description in the message body, in the case of a rejected search (as opposed to a failed one, for which an AI investigation will be necessary regardless)

**Comment by benbelow** [comment]
@mmelchers #691 should resolve this problem for expected errors e.g. validation failures. As such I'm going to close this card - please re-open and reply if you think there's something in this card that *isn't* covered by #691 and still needs resolving
