### ISSUE TITLE
searches fail when trying to run standard set of patients with real HLA

### ISSUE THREAD

**Issue by mmelchers** [Anthony-Nolan/Atlas#685]
When running a standard set of patients with the recommended database settings I notice the following: 

-many searches fail the first time and need one or more extra tries in order to finish
-many of these searches never finish at all. Out of a set of 50 5 locus HR patients only 16 finished. This is totally unacceptable.

**Comment by benbelow** [comment]
> -many searches fail the first time and need one or more extra tries in order to finish

this has been covered elsewhere, it's a trade-off of using a database with auto-pause enabled, and won't be present in a system without auto-pause.

> -many of these searches never finish at all. Out of a set of 50 5 locus HR patients only 16 finished. This is totally unacceptable.

I would expect this to be fixed with the recent performance improvements. 

@mmelchers please could you confirm whether you've seen the same behaviour in your more recent testing?

**Comment by benbelow** [comment]
We haven't seen this come up again post recent performance improvements, all performance tests so far have succeeded outside of HLA validation issues. 

I'm going to close this issue, we can re-open or open a similar one if we find that searches are failing in further acceptance testing by WMDA
