### ISSUE TITLE
Repeat search - changes in match prediction results not caused by a donor update

### ISSUE THREAD

**Issue by benbelow** [Anthony-Nolan/Atlas#752]
Currently repeat search only reports on differences in the full set of matching donors - i.e. whether there are any new donors added to the results, or any previous results are no longer a match. 

It will not re-run match prediction for donors that were and still are a match. This means that match prediction results should be considered a snapshot of the donor at the time the original search was run, and not always trusted in perpetuity.

Ways this could change without a donor HLA update:

* Donor is now mapped to a different HF set.

* Donor is mapped to the same HF set, but HF set has been updated.

* A more specific HF set has been uploaded since the search, that the donor/patient would now use.

**Comment by zabeen** [comment]
Not sure the above ticket description in 100% accurate, we do report previously matched donors that have been updated since the cut-off date, and match prediction is calculated for both them and the new donors ([link to code](https://github.com/Anthony-Nolan/Atlas/blob/f891ab775af2051e50815ea6ebeaf2c46e037a30/Atlas.RepeatSearch/Services/Search/RepeatSearchRunner.cs#L104)).

However, it is true that uploading a new HF set, or modifying the mapping of HF sets will not cause the affected donors to be eligible for repeat search.

**Comment by zabeen** [comment]
I am closing this ticket as there is no requirement to make donors eligible for repeat search when a new HF set has been uploaded. Can re-create the ticket with exact requirements if it ever comes up.
